### ISSUE TITLE
Donnot support IDEA 2016 ?

### ISSUE THREAD

**Issue by sunaowei** [igorspasic/idea-sexyeditor#13]
I installed it on IDEA 2016.2 ,but I cannot find it in 'Other Setting'.

**Comment by igorspasic** [comment]
Did you tried: `Preferences` > `Other settings` > `SexyEditor` ?
Im just looking it?

**Comment by igorspasic** [comment]
@sunaowei did you find it?

**Comment by sunaowei** [comment]
Beacuse  I donnot update this plugin,I try update it  ,now it works fine ,Thank you very much.

**Comment by igorspasic** [comment]
All good! Enjoy!
